image:
  file: .gitpod.Dockerfile

ports:
  - port: 5000
    visibility: public
    onOpen: open-preview

tasks:
  - command: python src/main.py

vscode:
  extensions:
    - ms-python.python
    - cweijan.vscode-database-client2
    - https://github.com/guilatrova/flask-sqlinjection-vulnerable/raw/main/thunder-client-1.9.1.vsix
    - vscode-icons-team.vscode-icons
    - dracula-theme.theme-dracula
