image:
  file: .gitpod.Dockerfile

ports:
  - port: 5000
    visibility: public
    onOpen: open-browser

tasks:
  - command: python src/main.py

vscode:
  extensions:
    - ms-python.python
    - vscode-icons-team.vscode-icons
    - robbowen.synthwave-vscode
    